### ISSUE TITLE
Set up some react project linting.

### ISSUE THREAD

**Issue by thiagodemellobueno** [Greenstand/treetracker-admin-DEPRECATED#15]
Just helps people not trip each other up.

Boo to airbnb but : https://github.com/airbnb/javascript/tree/master/react

**Comment by deepwinter** [comment]
@jparaujo Can we handling this as part of our CI/CD process?

**Comment by jparaujo** [comment]
I can investigate what Sonarcloud has or we might run ESLint on Jenkins too.
