### ISSUE TITLE
Implement routing

### ISSUE THREAD

**Issue by thiagodemellobueno** [Greenstand/treetracker-admin-DEPRECATED#22]
It's really easy to implemet routing, browser history as state, and deeplinknig usig react-router 

https://redux.js.org/advanced/usage-with-react-router

**Comment by gloriaLVela** [comment]
Test

**Comment by gloriaLVela** [comment]
I would like to work on this issue

**Comment by thiagodemellobueno** [comment]
@gloriaLVela - hello, You are most welcome to do so!
Have you chatted with us on our slack? 
Pop in over here https://greenstand.slack.com/messages/C8W6GT9MZ so we can discuss.

Many thanks!
T

**Comment by thiagodemellobueno** [comment]
@gloriaLVela - hello, let's do it!

**Comment by gloriaLVela** [comment]
I am writing the Router but I need help finding the style sheets.

**Comment by sebastiangaertner** [comment]
is it treetracker-admin/src/index.css ???

**Comment by thiagodemellobueno** [comment]
There are a couple of css files App.css for example, but as with most things JS theres a bit of a change in paradigm.

We’re using material-ui and this is how styling is handled:
https://material-ui.com/customization/css-in-js/ <https://material-ui.com/customization/css-in-js/>

See line 18 here:
https://github.com/Greenstand/treetracker-admin/blob/master/src/components/molecules/AppDrawer/AppDrawer.js

**Comment by gloriaLVela** [comment]
Can we use the style sheet for GreenStand.org?

**Comment by thiagodemellobueno** [comment]
Can you elaborate on why we need stylesheets for implementing routing?
What are you trying to achieve re: styling?

**Comment by gloriaLVela** [comment]
Yes, I would like to follow the same style as the one in GreenStand.org. Is that ok?

**Comment by sebastiangaertner** [comment]
I am working on a redesign of the site this coming week. Not much will change. The color codes are set.

**Comment by thiagodemellobueno** [comment]
I’m just not certain what that has to do with implementing routing.

**Comment by thiagodemellobueno** [comment]
I would just ask that if we submit a PR for routing, it only include code that takes care of routing.
 
That way we can make sure the pull requests only contain the code relevant to specific issues, it’s much easier to QA, and merge that way. 

If you want to create a ticket about incorporating certain styles into the admin interface I recommend doing that.
But I would be careful with shoehorning traditional css with material-UI in ways that may cause unpredictable or hard to debug behavior.

**Comment by gloriaLVela** [comment]
The Router is plain and has a few options.
