### ISSUE TITLE
Tree Image gallery for quick reviewing and disabling of fake tree entries....

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-DEPRECATED#32]

**Comment by jparaujo** [comment]
About my suggestion to use AI
https://greenstand.slack.com/archives/C8W6GT9MZ/p1528157040000043

**Comment by thiagodemellobueno** [comment]
@jparaujo  - do you see tree images being broken out into their own api top level object, and then being simply associated with trees? this may make some things easier (less parsing when only the image matters)

**Comment by thiagodemellobueno** [comment]
Possibly of use in these efforts: https://www.npmjs.com/package/react-masonry-component

**Comment by jparaujo** [comment]
That's a nice one. I'm currently experimenting with this: https://bvaughn.github.io/react-virtualized/#/components/Masonry

But having issues on auto positioning. I'm guessing it's something related with the Material theme we have in place. I will find out tonight. Haven't had much time to invest since our last meeting...

**Comment by thiagodemellobueno** [comment]
No worries, just doing a little garden tending.

**Comment by sebastiangaertner** [comment]
Looks good. If even I understand the package code... 
--
Sent from myMail for Android Wednesday, 20 June 2018, 02:49PM +01:00 from Thiago de Mello Bueno  notifications@github.com :

**Comment by thiagodemellobueno** [comment]
I see a series of subtasks we can break out.

- [ ] Query trees with images
- [ ] Wire up checkbox selection (see tree table)
- [ ] Wire up unpublish button (send query)
- [ ] Wire up delete button (send query)
- [ ] Set up [masonry listing](https://bvaughn.github.io/react-virtualized/#/components/Masonry_) with thumb
