### ISSUE TITLE
Fix icon active state state bug.

### ISSUE THREAD

**Issue by thiagodemellobueno** [Greenstand/treetracker-admin-DEPRECATED#47]

**Comment by nimblefox** [comment]
@thiagodemellobueno - I've made a PR #51 with a fix for the inactive state. When you have a moment can you take a look.

**Comment by ZavenArra** [comment]
For image scrubbing, we won't be needing a deeplink to particular page.  When images are approved or rejected, they be disappearing from the scroller.  The idea of infinite scroll is to be able to quickly scan image for rejects.
