### ISSUE TITLE
Introduce Certificate to Api Models and Tree Details View (App Drawer)

### ISSUE THREAD

**Issue by thiagodemellobueno** [Greenstand/treetracker-admin-DEPRECATED#50]

**Comment by madhu-kumari** [comment]
Hi...I would like to work on this issue. Is it possible for you to provide more information on this requirement?

**Comment by thiagodemellobueno** [comment]
With this PR:
https://github.com/Greenstand/treetracker-admin/pull/52
(Which has been merged)
@nimblefox  has introduced the tree details drawer, and done some preliminary rendering of the same.

As for getting the "relation" information back from the api here is some documentation:
https://loopback.io/doc/en/lb2/Querying-related-models.html
https://loopback.io/doc/en/lb2/Include-filter.html

So this issue becomes more about  updating the queries to `include` the related data, and echo it in the app drawer, which is now pretty straightforward.

**Comment by thiagodemellobueno** [comment]
Please consider #49 as well :)

**Comment by madhu-kumari** [comment]
I would like to clarify my understanding. Let me know if I am doing anything wrong.

1) Take fresh code from the repository.
2) npm install
3) npm start
4)Check the live server at localhost:3000
5) Select any id, a panel from the right side appears
6) The panel contains a tree image, and 3 other details (Location, Status, Missing )
7) Do I need to modify the API and get additional information that needs to be displayed in this panel?
If yes, what other parameters I need to fetch (any API level changes)? 
8) Or do I need to just render the API and fetch values (No API level changes)?
9) Once these values are fetched, they need to be displayed in the same tree panel with the 3 other details.

**Comment by madhu-kumari** [comment]
Thanks for providing the loopback docs. will try to get hands-on.

**Comment by thiagodemellobueno** [comment]
Hello @madhu-kumari. As per a quick conversation with @deepwinter (Zaven), the way we are now talking about "grouping" a tree by donor is a `certificate` see `certificateId`  - see - `http://dev.treetracker.org/api/admin/Trees/6 `
trees do have `donor` but "you get the donor by joining the certificates and donors table" - so we'll probably need to expose both donors and certificates in the api over at `common/models.`

**Comment by thiagodemellobueno** [comment]
https://files.slack.com/files-pri/T6WR1QS8J-FD20MDTHP/image.png

**Comment by gloriaLVela** [comment]
Migrated new number #22
